### ISSUE TITLE
Clean up labelling

### ISSUE THREAD

**Issue by alistair-marshall** [alistair-marshall/cFIREsim-open#19]
Labeling stuff that has nothing to do with the actual tool:

1. Change "extra income/savings" to "other income/savings". Same with "extra spending" -- "other spending" is clearer.
2. Label the amount fields consistently and with a temporal component for clarity -- something like "Annual Amount ($)".

https://www.reddit.com/r/financialindependence/comments/fvsowu/updating_cfiresim/fml2nzd/?context=3

**Comment by jcoliz** [comment]
If you think of anything else here you'd want to see cleaned up before closing this issue, please comment here. I'll be happy to go in here and do any more cleanup as needed.

**Comment by alistair-marshall** [comment]
No, I am happy to close out. Thanks.
