### ISSUE TITLE
Variable CAPE never fails

### ISSUE THREAD

**Issue by mcolyer** [alistair-marshall/cFIREsim-open#23]
@alistair-marshall thanks for getting this working. I did run across something odd with the variable-cape spending plan and wanted to file this issue.

## Steps to reproduce

- Reload the page to the defaults
- Select Variable CAPE
- Add terms of 0.4* and 0.02+
- Spending floor: 500,000

## Result
100% success

## Expected result
Less than 100% (given that the starting portfolio is 1m)

**Comment by alistair-marshall** [comment]
Interesting, it seems to ignore the spending floor once the portfolio dropps below the critical amount and spends 0 in the final years.

Thanks for pointing it out.
