### ISSUE TITLE
Consider removing link to cFIREsim forums

### ISSUE THREAD

**Issue by jcoliz** [alistair-marshall/cFIREsim-open#51]
They're old and they're locked.

**Comment by alistair-marshall** [comment]
Completely agree.

Any other links worth removing/adding/updating?

**Comment by jcoliz** [comment]
The calculators & blogs/forums could benefit from an update. It would require a little research project.

There are a bunch of new calculators out there. One could scour the forums and link to the new ones. 

/r/financialindependence/ definitely deserves a mention.

There once was a list of blogs on the sidebar of that subreddit, I seem to recall, but can't find it now.
