### ISSUE TITLE
Model taxes?

### ISSUE THREAD

**Issue by lutorm** [alistair-marshall/cFIREsim-open#60]
It's not at all clear to me what assumptions, if any, are made about taxes now. Like, is the portfolio gain just pre-tax and I should include taxes under my spending plan? That's hard to do, since I don't know how much the realized gain is in a given year. It would be great if you could input assumptions about the capital gains tax rate.

(Maybe for most US retirees, cap gains will be small in retirement, but we are considering moving to a country with a flat 30% cap gains tax, so it will definitely matter there.)

**Comment by alistair-marshall** [comment]
The current implementation makes absolutely no tax assumptions. Everything is just pre-tax.

One of the other forks was looking at adding taxes, but it was adding US tax which was of no use to myself.
Considering how complex any individual countries tax system is, I have no idea how to model taxes in a generic way that would work for many countries.

It is not something I intend to work on, though if yourself or anyone else does add it (without making the interface too complicated), I would be happy to accept a pull request.
